### ISSUE TITLE
生成2的N次幂sprite图

### ISSUE THREAD

**Issue by ChriXChan** [gkajs/gka#31]
用--ratio 2不能实现，有其他命令？或者要自行实现模板？

**Comment by joeyguo** [comment]
gka不生成多倍图；--ratio 指提供n倍图，然后处理生成对应的动画

**Comment by ChriXChan** [comment]
那想要输出2的N次幂sprite图有其他实现方法吗？

**Comment by joeyguo** [comment]
估计要找找有没有其他工具。
