### ISSUE TITLE
是不是mac环境下用不了？

### ISSUE THREAD

**Issue by ymzuiku** [gkajs/gka#6]
![image](https://user-images.githubusercontent.com/3291900/30513732-04d75342-9ace-11e7-9960-b7e733688d4c.png)
![image](https://user-images.githubusercontent.com/3291900/30513734-0e0ab300-9ace-11e7-8fed-04a0cd658c62.png)
如图，在生成的gka-icon-u-normal文件夹或gka-icon-u-canvas里，只有img文件夹，没有其他文件。
使用命令:
$gka ./icon -t

**Comment by joeyguo** [comment]
@ymzuiku

**Comment by joeyguo** [comment]
有问题可以联系我，详细沟通哈 QQ 3201590286
