### ISSUE TITLE
生成多张合并图片

### ISSUE THREAD

**Issue by sitianming** [gkajs/gka#7]
我有个需求，有260张连续图片，希望生成多张4*3的合并图。
目前，如果使用-s合并，只能生成一张270M的图片，没法使用

**Comment by joeyguo** [comment]
hi，sitianming. 生成多张合图在计划中，我现在国外，会尽快支持：D。请问 4*3 的比例是有什么原因吗？

**Comment by joeyguo** [comment]
@sitianming 麻烦更新一下 gka v2.4.0，加入参数 --count <number> ，指定每几张图片合成一张合图。生成多张合图及相关代码，相关文档已更新 README

**Comment by cfxmj2014** [comment]
gka@2.8.3 --count不生效
