### ISSUE TITLE
gka tool 命令输出无 css 文件

### ISSUE THREAD

**Issue by aNd1coder** [gkajs/gka#8]
无法像 `gka` 命令一样生成 css 文件

**Comment by joeyguo** [comment]
@aNd1coder gka tool 只做图片处理，可选生成信息文件。生成 css 文件的话可以使用 gka 命令哈~

**Comment by aNd1coder** [comment]
@joeyguo 正常的合并图片（图片空白裁剪）然后导出帧动画 css

**Comment by joeyguo** [comment]
@aNd1coder 是想空白裁剪和合图？
是的话可以使用 gka 命令，且使用这个模板 [gka-tpl-cs](https://github.com/gkajs/gka-tpl-cs)

**Comment by aNd1coder** [comment]
@joeyguo 多谢，好用！
